

import Foundation

struct InfoMiopiaVCText {
    
    let segmentedContrItem1 = ["en_US": "Information", "ru_Ru": "Информация"]
    let segmentedContrItem2 = ["en_US": "Instruction", "ru_Ru": "Инструкция"]
    
    let myopiaDescrLabelText = ["en_US": "  Nowadays myopia is the most frequent  cause of low vision in  humans.\n\n  Entering the eye rays of light focus on the retina being intensively bented by cornea and lens.\n The reason of low vision in myopia is a mismatch between the optical power of the eye and the  eyeball length, so   light rays form an image before they reach the retina.",
                                "ru_Ru": "   Близорукость, или миопия – самая распространенная причина низкого зрения у человека в наши дни. \n\n   Попадающие в глаз лучи света фокусируются до сетчатки, когда роговица и хрусталик чрезмерно сильно изменяют их ход. \n    Человек плохо видит при миопии из-за несоответствия силы оптики глаза и размера глазного яблока, при котором лучи света формируют изображение раньше, чем они достигнут сетчатки. И когда они все-таки попадают на нее, то картинка становиться размытой."]
    
    let ahtungLabelText = ["en_US": "Attention!", "ru_Ru": "Внимание!"]
    
    let attantionLabelText = ["en_US": "Normally  the point of clear vision is located at infinity. For the human eye infinity begins at 5 meters: if an object is located more than 5 meters away, parallel rays focus on the retina of normal eye . That is why this distance is chosen for visual acuity measurement.",
                              "ru_Ru": "   При нормальном зрении точка ясного видения находится как бы в бесконечности. Для человеческого глаза бесконечность начинается на расстоянии 5 метров: при расположении предмета не ближе 5 метров на сетчатке глаза с нормальным зрением собираются параллельные лучи. Именно поэтому проверку остроты зрения осуществляют с такого расстояния."]
    
    let tableDescrLabelText = ["en_US": "The visual acuity in contact lenses or eye glasses exam or in routine eye examination is measured with special charts. There are various eye charts,  but generally visual acuity check involves following:\n 1. A person seats at a certain distance away from an eye  chart.\n 2. A doctor indicates a line or symbol on the table and asks the person to name it.\n 3. If   the indicated symbol is clearly distinguished by the person, doctor asks to name a smaller one.",
                               "ru_Ru": "   Чтобы определить остроту зрения человека, подбирая контактные линзы, очки или ради профилактики, применяют специальные таблицы, которые бывают разных видов. Но в целом процедура диагностики происходит по одному принципу:\n 1. Человека усаживают напротив таблицы на определенном расстоянии.\n 2. Врач указывает на строку или символ на таблице, просит человека его назвать.\n 3. Если человек хорошо может различить указанный символ, врач указывает на более мелкий шрифт."]
    
    let firstLabelText = ["en_US": "The application (myopia test) uses Landolt's optotypes (symbol 'C') and Snellen's optotypes (symbol 'Ш').",
                          "ru_Ru": "   В приложении (в тесте на наличие близорукости)  используются оптотипы Ландольта (символ 'С') и оптотипы Снеллена (символ 'Ш')."]
    
    let landoltLabelText = ["en_US": "Landolt's optotypes are diversly sized black rings  in various sizes with gaps oriented in various directions , and the minimal angle of resolution of the eye can be established upon the ability to recognize the gap orientation.",
                            "ru_Ru": "Оптотипы Ландольта по форме представляют собой черные кольца разной величины с разрывами, обращенными в разные стороны, и по распознаванию этого разрыва можно определить минимальный угол разрешения глаза."]
    
    let symbolDescrButtonTitle = ["en_US": "Learn more about optotype sizes.",
                                  "ru_Ru": "Подробнее о размерах символа."]
    
    let secondLandoltLabelText = ["en_US": "The  Landolt ring width and the gap width is 5 times smaller than its outer diameter, the ratio of these parameters is 5: 1: 1. An optotype  gap can be oriented in  four directions (up, down, right and left).",
                                  "ru_Ru": "Ширина кольца Ландольта и ширина разрыва в 5 раз меньше его наружного диаметра, то есть соотношение этих параметров – 5 : 1 : 1. Направление разрыва кольца может иметь четыре варианта (вверху, внизу, справа и слева)."]
    
    let snelenLabelText = ["en_US": "Snellen's optotype is a squared figure similar to the letter 'Ш' and it can be oriented in 4 directions. These optotypes are widely used in ophthalmology.",
                           "ru_Ru": "Оптотип Снеллена - вписанная в квадрат фигура, подобная букве 'Ш', которая может иметь 4 ориентации. Такие знаки также широко используются в офтальмологии."]
    
    let howDoTestLabelText = ["en_US": "Position the phone at a distance  specified  in the application settings. You will name the directions of an optotype to your assistant, and your assistant will  press appropriate buttons on the phone screen.",
                              "ru_Ru": "   Расположите телефон на расстоянии, уcтановленном в настройках приложения. Называйте направления символа вашему ассистенту, который будет нажимать соответствующие кнопки на экране телефона. "]
    
    let symbolDiscrLabelText = ["en_US": "Landolt's optotypes are black C-rings in different sizes with gaps in various  directions. The minimal angle of resolution of an eye can be determined according to the ability to recognize the gap orientation. The gap can be oriented in 4 directions (up, down, right and left)",
                                "ru_Ru": "Оптотипы Ландольта по форме представляют собой черные кольца разной величины с разрывами, обращенными в разные стороны, и по распознаванию этого разрыва можно определить минимальный угол разрешения глаза.  Направление разрыва кольца может иметь четыре варианта (вверху, внизу, справа и слева)"]
    
    let stopBtnDiscrLabelText = ["en_US": "When it is impossible to determine gap direction , press the  '❌' button. The exam will end and the results will be saved. You will be asked to repeat the test for   the other eye. If you quit before the test is finished, the results will be canceled.",
                                 "ru_Ru": "Когда невозможно определить в какую сторону направлен символ - нажмите кнопку с символом '❌'. Тест будет остановлен, результат сохранится. Вам будет предложено пройти тест для другого глаза. Если Вы выйдете до окончания теста - результаты сохранены не будут."]
    
    let actionBtnLabelText = ["en_US": "If you can tell the optotype direction, your assistant will press on the button you are naming.\n  If the direction of the symbol and the arrow on the button coincide, a smaller symbol will appear.",
                              "ru_Ru": "Если Вы можете различить в какую сторону направлен символ - Ваш ассистент должен нажать на кнопку, которую Вы ему назовете. \n В случае совпадения направления символа и стрелки на кнопке  - появится символ более мелкого размера. "]
    
    let deviceDetectLabelText = ["en_US": "Device on which the application is running.  The size of optotypes  for vision acuity test is calculated depending on the device screen width.",
                                 "ru_Ru": "Устройство, на котором запущено приложение. В зависимости от ширины экрана устройства происходит расчет размеров символа для определения остроты зрения."]
    
    let distanceDiscrLabelText = ["en_US": "The distance set for the test. The size of optotypes for vision acuity test is calculated depending on the chosen distance. You can change checkpoint distance in the application settings.",
                                  "ru_Ru": " Расстояние, установленное для проведения теста. В зависимости от расстояния происходит расчет размеров символа для определения остроты зрения. Изменить расстояние проведения теста можно в настройках приложения."]
    
    let howDoRecognLabelText = ["en_US": "To recognize speech, turn on the speech recognition toggle switch in the application settings. Also set the time you need to reach your checkpoint away from the phone.\n When the speech recognition feature is turned on, the myopia test can be performed without an assistant.\n Please use a wireless headset (Apple AirPods 2).",
                                "ru_Ru": "Для распознавания речи включите соответствующий переключатель в настройках приложения. Также установите время, которое Вам потребуется чтобы отойти от телефона на установленное расстояние.\n \nПри включении распознавания речи тест на наличие миопии можно проводить самостоятельно.\n Необходимо использовать беспроводную гарнитуру.\n "]
    
    let speechSymbolDiscrLabelText = ["en_US": "If you can distinguish the symbol orientation, name it into the headset microphone: 'right', 'left', 'top' or 'bottom'. If you have named 3 out of 4 directions correctly, a smaller symbol will appear on the screen. If you can’t recognize the direction of the symbol, say 'STOP'. The test will end. The result will be saved.",
                                     "ru_Ru": "Если Вы можете различить в какую сторону направлен символ - произнесите в микрофон гарнитуры направление символа: 'вправо', 'влево', 'вверх' или 'вниз'. Когда Вы правильно назвали 3 из 4-х направлений - на экране появится символ более мелкого размера. Если невозможно определить направление символа - произнесите слово 'СТОП'. Тест завершится. Результат будет сохранен."]
    
    let lineDescrLabelText = ["en_US": "There is a remaining time indicator showing time left until next optotype.",
                              "ru_Ru": "Индикатор оставшегося времени до момента появления нового символа."]
    
    let howDoAutoDetectLabelText = ["en_US": "Turn on the automatic distance detection switch in the application settings. For correct automatic distance determination the room light should be good enough.\n Set the time you need to move to the checkpoint.\n\n  In case of determining the distance from the screen there should be only  one person standing in front of the phone camera:\n\n 📱    →    🧍 = ✅\n\n If there is more than one person in the screen, the distance may be determined incorrectly:\n\n 📱    →    👫 = 🚫 \n\n  Thereafter testing coincides with the regimen described for  speech recognition feature.",
                                    "ru_Ru": "  Включите в настройках приложения переключатель автоматического определения расстояния. Для автоматического определения расстояния в помещении должно быть хорошее освещение.\n Установите время, которое Вам потребуется, чтобы отойти на планируемое расстояние.  \n\n!!!  При определении расстояния в кадре должно быть не более одного человека, стоящего лицом к фронтальной камере телефона:\n\n 📱    →    🧍 = ✅   \n \n Если будет более одного человека - расстояние может быть определено некорректно:\n\n 📱    →    👫 = 🚫 \n\n  Далее тест проводится также как при включенном распознавании речи."]
    
    
    
}
